import type { Metadata } from "next";
import { Inter } from "next/font/google";
import 'swiper/css';
import 'swiper/css/navigation';

import '@/assets/styles/variables.scss'
import '@/assets/styles/normalize.scss';
import '@/assets/styles/globals.scss'
import '@/assets/styles/swiper.scss'
import Header from "@/components/Layout/Header/Header";
import Footer from "@/components/Layout/Footer/Footer";
// import 'react-accessible-accordion/dist/fancy-example.css';


const inter = Inter({ subsets: ["cyrillic", "latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  inter.style.fontWeight = 700;
  return (
    <html lang="ru">
      <body className={inter.className} >
      <Header />
      {children}
      <Footer />
      </body>
    </html>
  );
}
