name: Deploy

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout кода
        uses: actions/checkout@v2

      - name: Connect to server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/somebody/cs/domdoctor/
            git pull
            export PATH="$PATH:/home/somebody/.nvm/versions/node/v20.11.0/bin"
            npm i
#            /home/somebody/.nvm/versions/node/v20.11.0/bin/npm run build
#            /home/somebody/.nvm/versions/node/v20.11.0/bin/pm2 start npm -- start